### ISSUE TITLE
why bazel?

### ISSUE THREAD

**Issue by vib-hor** [zml/zml#63]
Hey team!
Congratulation on amazing launch. I really like the feature of **_zml_** being able to define model architecture in Zig and creating inference artifacts for different target architectures.
@renerocksai's talk at Zigtoberfest does give some answers to the question "why bazel?" (one of which I like the most is:  sand-boxing the _inference-build-environments_).
**I'm not familiar with ROCm; that being said (and CMIIW):**
Zig's build system should be able to compile or link-with the vendor provided C/C++ libraries (e.g. [cuDNN](https://github.com/NVIDIA/cudnn-frontend))
which brings me back to the question"why bazel?"

**Comment by gwenzek** [comment]
* we have C++ dependencies using Bazel: mlir and openxla. Buiding those with `build.zig` would be a huge undertaking, and a maintenance nightmare.
* Bazel provides better sandboxing than `build.zig`, it's harder to accidentally depend on "/usr/lib/cuda.h" 
* Bazel binaries are byte to byte reproducible: `/home/gwenzek` doesn't appear in a Bazel binary, but does with build.zig.
* Bazel has a broader ecosystem, eg the `oci` rule that can build containers
* @steeve loves Bazel

That said, we acknowledge this is a controversial decision within the Zig community, and we are thinking of ways we can make it easier to integrate in a regular zig project. See #67 for some ideas.

build.zig is great and I like the idea of being able to extend the build system by just writing a little bit of Zig, instead of having to learn Skylark which is almost Python but not totally. They share some similar design patterns, that's why I'm confident we can make some bridges. build.zig is also improving fast and some of the pain points above have been expressed by others and may be solved in the future.

Please let me know if you have more questions, I'll be closing this otherwise.

**Comment by vib-hor** [comment]
I agree, taking in and maintaining those dependencies would be a nightmare. Case in point: [pytorch](https://github.com/pytorch/pytorch/tree/main/third_party) and [tensorflow](https://github.com/tensorflow/tensorflow/tree/master/third_party) (and jax), all btw use bazel but are great at hiding it from the users (or maybe just from me).
The goal of this question was to understand the dependencies that come with zml. For anyone familiar with zig and it's build system, it's seems odd to use a third-party build system for building a zig codebase. At the same time for anyone familiar with ML deployment ecosystem, it is amazing to see what zml is able to do with bazel along with the niceties of zig (upfront memory allocation and tagged tensors to name a few).

Dumping some resources I stumbled on while trying to understand on how one would approach creating inference artifacts directly with zig:
- Zig source code targeting different architectures ([here](https://github.com/ziglang/zig/tree/master/src/arch) and [here](https://github.com/ziglang/zig/blob/master/lib/std/Target.zig)). running `zig targets` shows a list of possible targets (I believe not all are supported). Maybe someday (probably never) zig itself can support this and all this would be irrelevant.
- Nice project which uses "Zig to drive the GPU" : https://github.com/gwenzek/cudaz

and some ziggit threads:
- https://ziggit.dev/t/advice-on-linking-cuda-to-zig/2405
- https://ziggit.dev/t/massively-parallel-programming-in-zig-more-gpu-support-incoming/1363

**Comment by gwenzek** [comment]
https://github.com/gwenzek/cudaz that's from me actually :-) note that in this project I didn't attempt to package cuda at all, and "left it as an exercise to the reader".

it's true that other project like jax use bazel behind the scene and only share pre-built artifact + a python wrapper. We are actually not so far away of being able to do smth similar since we are also pre-building some of our dependencies now.

**Comment by vib-hor** [comment]
Yes, I noticed ;). Seems like a great project to learn parallel programming with zig.

Indeed, Python ML libraries bundle pre-compiled artifacts in the wheels. It's on the user to get the correct wheels for the target architecture. In practice everything gets pulled with a single `pip install`.
Something similar might be possible with `build.zig` and `build.zig.zon`, where user must specify targets and all the pre-compiled dependencies gets pulled and cached during first compilation. In this way the linking is done by zig, and bazel only gets called when needed. 
Of course, the bazel features you mentioned will be gone, so I'm not sure if this would really be the way to go.

**Comment by GaetanLepage** [comment]
Thanks for the context! By curiosity, have you considered Nix as an alternative approach? It brings a decent support for the CUDA ecosystem. However, it does not provide caching within a single build (like bazel does).

**Comment by cerisier** [comment]
Hey @GaetanLepage, happy to see you here ! is the question targeted at @vib-hor or @zml?

If the question is for @zml, my answer would be that Nix and Bazel are not alternatives to each other, because they operate at different levels.

ZML uses Bazel as a build system and action graph execution engine.
This gives us perks where most other systems fall short:

1.	Compile everything from source within a single action graph, with a single build system.
2.	Be extremely granular about what is pulled into the graph, and therefore what is pulled into the artifact.
3.	Distribute compilation on remote executors (our graph usually span thousands of machines), which is important because of 1).
4.	Operate at the toolchain level within the same action graph (making changes to the compiler easily, and trivially adding new cross-compilation targets).
5.	“It just works” <- personal statement

To extend a bit on those:

### Single action graph

ZML stitches together very large heterogeneous environments (Zig, C, C++, Rust, various asm), as well as things like Python or Shell as part of the build orchestration, into a single action graph.
Having a single action graph gives total control over what is compiled, and how it is compiled, across all these environments.
Our users have this control too.

We operate on the full transitive source closure of our dependencies. Modifying upstream code like LLVM or OpenXLA is common.

For practical reasons, especially for users, we also provide prebuilts for various dependencies to avoid pushing massive builds onto the user side.

A simplified graph looks like this:

```
  |-- //ffi:cc
  |-- //mlir:c
  |   `-- @llvm-project
  |-- //platforms/cpu:libpjrt_cpu
  |-- //platforms/cuda:libpjrt_cuda
  |   `-- @libpjrt_cuda
  |       |-- //platforms/cuda:compat_probe
  |       `-- @cuda_cudart
  |-- //platforms/neuron:libnrt_headers
  |-- //platforms/neuron:libpython
  |-- //platforms/rocm:libpjrt_rocm
  |   `-- @libpjrt_rocm
  |-- //platforms/tpu:libpjrt_tpu
  |   `-- @libpjrt_tpu
  |-- //tools:xspace_to_perfetto_lib
  |-- //upb:upb_c
  |-- //zml/tokenizer/hftokenizers:hftokenizers_cc
  |-- //zml/tokenizer/sentencepiece:sentencepiece_swig
  |   |-- //zml/tokenizer/sentencepiece:sentencepiece_swig.swig
  |   `-- @com_google_sentencepiece
  |       `-- //third_party/com_google_sentencepiece:absl
  |-- //zml:posix
  |-- @compiler-rt
  |-- @flashattn
  |-- @iree
  |-- @libpjrt_neuron
  |   `-- @aws-neuronx-runtime-lib
  |-- @linenoise
  |-- @shardy
  |-- @stablehlo
  `-- @xla
      `-- @tsl
          |-- @eigen_archive
          |-- @farmhash_archive
          |-- @ml_dtypes_py
          `-- @zlib
```

### Remote execution

The source set on which we operate is so wide that compiling it on a single machine is simply not practical.
Bazel offers remote execution as a first-class feature. It is usually hard to get right, but because we treat 100% of our dependencies as hermetic inputs (zero implicit dependencies), we are able to trivially defer the compilation graph to remote executors and benefit from maximum cache hits. We do this constantly.

To give you an idea, the total number of lines of code that we compile within our graph exceeds 43M LoC. We are able to distribute that compilation across more than 2,000 remote executors. Cold builds take 2-3 minutes on average. Cache hit rate is almost 100% on every build.

Example with a build where we build LLVM (after a deep nested change) to build the Zig compiler, itself being used to compile a program for a new chip usually unknown to both:

<img width="977" height="209" alt="Image" src="https://github.com/user-attachments/assets/66270715-0b2d-420a-ad24-6e1c21a89338" />

### Tweaking the toolchain

We make extensive use of toolchain resolution.
For remote execution, we commonly build Linux x86 from macOS, using Linux ARM executors, while still being able to make changes to compiler code.

As a side perk, adding a new cross-compilation target is trivial if the compiler supports it, and still affordable even if it does not.

We patch LLVM both in target platform code and at the compiler level, for example to support chips on LLVM@HEAD even though LLVM does not know about them yet. We make patches in the Zig compiler source set for the same reasons.

<img width="533" height="56" alt="Image" src="https://github.com/user-attachments/assets/40c9f223-09c2-4ed2-a508-cd1b73bfefe9" />

### Sandbox granularity

Because the graph is fully declarative and hermetic, we can sandbox at a very fine granularity and know exactly what each action sees and depends on.

This is particularly true for CUDA (which we sandbox as part of the final ZML binaries), where we only download the parts that are interesting to us (thank you for the star on https://github.com/hermeticbuild/cuda-toolkit ❤️) and link against carefully chosen libraries. Only those libraries make it to the final artifact (.runfiles directory for local dev, Docker image in other scenarios).

An example sandbox (excluding glibc which we control on per target environment basis thanks to https://github.com/hermeticbuild/hermetic-llvm)
```
bazel-bin/examples/llm/llm.runfiles
├── +cuda_packages+libpjrt_cuda
│   └── sandbox
│       ├── bin
│       │   ├── compat_probe
│       │   ├── nvlink
│       │   └── ptxas
│       ├── lib
│       │   ├── compat
│       │   │   ├── libcudadebugger.so.1
│       │   │   ├── libcuda.so.1
│       │   │   ├── libnvidia-gpucomp.so.590.48.01
│       │   │   ├── libnvidia-nvvm70.so.4
│       │   │   ├── libnvidia-nvvm.so.4
│       │   │   ├── libnvidia-pkcs11-openssl3.so.590.48.01
│       │   │   ├── libnvidia-ptxjitcompiler.so.1
│       │   │   └── libnvidia-tileiras.so.590.48.01
│       │   ├── libcublasLt.so.13
│       │   ├── libcublas.so.13
│       │   ├── libcudart.so.13
│       │   ├── libcudnn_adv.so.9
│       │   ├── libcudnn_cnn.so.9
│       │   ├── libcudnn_engines_precompiled.so.9
│       │   ├── libcudnn_engines_runtime_compiled.so.9
│       │   ├── libcudnn_graph.so.9
│       │   ├── libcudnn_heuristic.so.9
│       │   ├── libcudnn_ops.so.9
│       │   ├── libcudnn.so.9
│       │   ├── libcufft.so.12
│       │   ├── libcupti.so.13
│       │   ├── libcusolver.so.12
│       │   ├── libcusparse.so.12
│       │   ├── libnccl.so.2
│       │   ├── libnvJitLink.so.13
│       │   ├── libnvrtc-builtins.so.13.1
│       │   ├── libnvrtc.so.13
│       │   ├── libnvshmem_host.so.3
│       │   ├── libnvtx3interop.so
│       │   ├── libpjrt_cuda.so
│       │   ├── libzmlxcuda.so.0
│       │   ├── libz.so.1
│       │   ├── nvshmem_bootstrap_uid.so.3
│       │   └── nvshmem_transport_ibrc.so.4
│       └── nvvm
│           ├── bin
│           │   └── cicc
│           └── libdevice
│               └── libdevice.10.bc
├── _main
│   ├── examples
│   │   └── llm
│   │       └── llm
│   ├── platforms
│       └── cpu
│           └── sandbox
│               └── lib
│                   └── libpjrt_cpu.so
|
├── MANIFEST
├── +non_module_deps+flashattn
│   └── flashattn
│       └── lib
│           └── libflashattn.so
└── _repo_mapping
```

### It just works

1.	Clone ZML.
2.	Install a 5 MB static Bazel wrapper binary.
3.	Run bazel build.
4.	It works, everywhere.

---

As a last word, Nix and Bazel are often opposed on the basis of hermeticity and reproducibility guarantees.
Nix offers this by design. Bazel does not.
However, Bazel expects reproducible actions and permits total hermeticity.
So if, like ZML, you treat your entire graph as fully hermetic, you also get reproducibility and all its perks (extreme cache hits during the build, byte-for-byte identical artifacts across runs and machines).
A good way to enforce this in Bazel is to use remote executors with fully blank images (not even glibc).

@Finistere who works at @zml is an avid Nix user and can probably answer further questions !

Thank you for your interest in ZML 🫶

**Comment by GaetanLepage** [comment]
Thanks a lot for the very detailed answer. I have since then watched the FOSDEM talk where you present your work around LLVM.
All of this is extremely impressive and I'll definitely be following what you are doing with ZML.

I'd be very interested to hear @Finistere 's take on the subject.

All the best!
